baseURL = "https://kenichi.shibata.co.uk"
languageCode = "en-us"
title = "Kenichi Shibata"
theme = "nix"

[params]
  Name = "Kenichi Shibata"
  HeaderUsername = "kenichi"
  HeaderHostname = "shibata.co.uk"
  About = "An innovative DevSecOps leader with over a decade of experience architecting and optimizing cloud infrastructure and security solutions. I excel at driving integration of cutting-edge practices into software development lifecycles to enhance security, reduce costs, and boost efficiency. My expertise has been recognized through speaking engagements at major events like AWS Summit, QCon, and Cloud Expo Europe. As the author of \"Cloud Native Monitoring\" and \"Cloud Native Observability\" (O'Reilly Media), and a regular contributor to technical publications, I'm passionate about sharing knowledge. I'm seeking an opportunity to leverage my extensive cloud security, DevOps, and authorship background to drive success for a forward-thinking organization."
  ProfilePicture = "https://avatars0.githubusercontent.com/u/13744098?s=460&u=21c703da9a2c23b2f6c15f81f82ae1f818ed26dc&v=4"
  GithubID = "kenichi-shibata"
  LinkedInID = "kenichishibata31"
  Email = "kenichi@shibata.co.uk"
  CvURL = "https://github.com/kenichi-shibata/kenichi-shibata/raw/master/Kenichi_Shibata_VisualCV_Resume.pdf"

[menu]
  [[menu.header]]
    name = "cv"
    weight = 0
    url = "/cv"

  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"
